name: flutterpp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  window_manager: ^0.2.8
  get_storage: ^2.0.3
  supabase_flutter: ^1.2.2
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  heroicons: ^0.7.0

# dev_dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
