name: flutterpp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^5.0.0-beta.52

# dev_dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
