name: flutterpp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  window_manager: ^0.3.4
  get_storage: ^2.0.3
  supabase_flutter: ^1.10.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  heroicons: ^0.8.0
  loading_animation_widget: ^1.2.0+4
  uuid: ^3.0.7
  flutter_svg: ^2.0.6
  # appflowy_editor: ^0.1.12
  # appflowy_board: ^0.1.0
  zoom_widget: ^2.0.1

# dev_dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
