name: flutterpp
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.6 <3.0.0"

# dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  window_manager: ^0.3.4
  get_storage: ^2.1.1
  supabase_flutter: ^2.3.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  heroicons: ^0.9.0
  loading_animation_widget: ^1.2.0+4
  uuid: ^4.3.3
  flutter_svg: ^2.0.6
  # appflowy_editor: ^0.1.12
  # appflowy_board: ^0.1.0
  expansion_tile_group: ^1.2.4
  google_fonts: ^6.1.0
  flex_color_picker: ^3.2.2
  sizer: ^2.0.15
  file_selector: ^1.0.2
  awesome_side_sheet: ^0.0.3
  device_frame: ^1.1.0
  flutter_platform_alert: ^0.5.1
  screenshot: ^2.1.0
  image: ^4.1.4
  process_run: ^0.14.1+3
  glowy_borders: ^1.0.2
  device_info_plus: ^9.1.1
  lottie: ^3.0.0
  json2yaml: ^3.0.1
  yaml: ^3.1.2
  widget_arrows: ^0.6.0
  graphite: ^1.1.2
  appflowy_editor: ^2.3.2
  emojis: ^0.9.9

# dev_dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/screenshots/
    - assets/templates/
    - assets/jsons/
    - assets/lottie/
