on:
  push:
    branches: [main]

name: Linux

jobs:
  build-linux:
    name: "Build Linux"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.6.1
        with:
          channel: "stable"

      - name: Install Linux build tools
        run: sudo apt-get update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev

      - name: Enable desktop
        run: flutter config --enable-linux-desktop

      - name: read yaml
        id: read_action_js
        uses: pietrobolcato/action-read-yaml@1.1.0
        with:
          config: ${{ github.workspace }}/pubspec.yaml

      - name: Create Version Number
        id: versions
        run: |
          echo "::set-output name=version::${{ steps.read_action_js.outputs['version'] }}"

      - name: Set FlutterPP.desktop version
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: FlutterPP.desktop
          contents: Version=${{ steps.versions.outputs.version }}
          write-mode: append

      - name: Set FlutterPP.desktop version (snap version)
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: snap/gui/FlutterPP.desktop
          contents: Version=${{ steps.versions.outputs.version }}
          write-mode: append

      - name: Set snapcraft.yaml version
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: snap/snapcraft.yaml
          contents: 'version: "${{ steps.versions.outputs.version }}"'
          write-mode: append

      - name: Flutter get packages
        run: flutter pub get

      - name: Flutter build app
        run: flutter build linux

      - name: Install appbuilder deps
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2 libgtk-3-0

      - name: Install appimagebuilder
        run: |
          wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage
          sudo mv appimage-builder-x86_64.AppImage /usr/local/bin/appimage-builder

      - name: Build AppImage
        run: |
          appimage-builder --recipe AppImageBuilder.yml

      - name: Upload Release Asset
        id: upload-release-asset
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: FlutterPP-latest-x86_64.AppImage
          asset_name: FlutterPP-linux-${{ steps.versions.outputs.version }}.AppImage
          tag: ${{ steps.versions.outputs.version }}
          release_name: Release ${{ steps.versions.outputs.version }}
