on:
  push:
    branches: [main]

name: Release Artifacts

jobs:
  build-macos:
    name: "Build MacOS"
    runs-on: macos-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.6.1
        with:
          channel: "stable"

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Enable desktop
        run: flutter config --enable-macos-desktop

      - name: Install Cider
        run: flutter pub global activate cider

      - name: Set new Flutter version
        run: cider version ${{ github.event.release.tag_name }}

      - name: Set release changelog
        run: cider release

      - name: Flutter get packages
        run: flutter pub get

      - uses: nickwph/apple-build-certificate-action@v1
        with:
          certificate-base64: ${{ secrets.PROD_MACOS_CERTIFICATE }}
          certificate-password: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
      - uses: nickwph/apple-provisioning-profile-action@v1
        with:
          profile-base64: ${{ secrets.PROD_MACOS_PEOVISION_PROFILE }}

      - name: Build MacOS
        run: flutter build macos --release
