on:
  push:
    branches: [main]

name: Windows

jobs:
  build-windows:
    name: "Build Windows for MS Store"
    runs-on: windows-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.6.1
        with:
          channel: "stable"

      - name: Enable desktop
        run: flutter config --enable-windows-desktop

      - name: Create Version Number
        id: versions
        run: |
          git fetch #2
          VERSION_WITHOUT_SUFFIX="$(grep 'version:' pubspec.yaml | awk '{ print $2 }' | cut -d'+' -f 1)" #3
          function parse_git_hash() {
            git rev-list --count origin/main
          } #4
          MAIN_COUNT=$(parse_git_hash) #5
          APP_VERSION="$VERSION_WITHOUT_SUFFIX" #6
          echo "::set-output name=version::$(echo $APP_VERSION)" #7

      - name: Write MSIX
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: pubspec.yaml
          contents: |
            msix_config:
              display_name: Flutter FlutterPP
              publisher_display_name: waqtollcapps.
              identity_name: waqtollcapps.FlutterPP
              publisher: CN=52C80A4B-6F71-430C-88F2-0AFF0C54D249
              msix_version: ${{steps.versions.outputs.version }}.0
              logo_path: assets\windwos.png
              architecture: x64
              capabilities: "internetClient,removableStorage"
              store: true
              build_windows: false
          write-mode: append

      - name: Flutter get packages
        run: flutter pub get

      - name: Flutter build app
        run: flutter build windows

      - name: Create MSIX
        run: flutter pub run msix:create

      - name: Upload MSIX to release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/windows/Runner/release/FlutterPP.msix
          asset_name: FlutterPP-windows-${{ steps.versions.outputs.version }}-MS-NS.msix
          tag: ${{ steps.versions.outputs.version }}
          release_name: Release ${{ steps.versions.outputs.version }}

      # TODO: Upload automatically to MS Store. MSFT is having some issues with their Azure AD so cannot be done yet.
